package com.epam.doable1.service;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.*;
import org.springframework.stereotype.Service;
import org.springframework.web.client.RestTemplate;

import java.util.List;
import java.util.Map;

@Service
public class LlmEmailService {

    private static final String GEMINI_URL =
            "https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=%s";

    private final RestTemplate restTemplate = new RestTemplate();

    @Value("${gemini.api.key:}")
    private String apiKey;

    /** Personalised intro paragraph for an employee reminder email. */
    public String employeeIntro(String employeeName, String courseName, String courseId) {
        String template = String.format(
                "Our records show that you have not yet completed the course <b>%s</b> (Course ID: %s). "
                + "We kindly request you to complete it at the earliest to stay on track with your "
                + "professional development goals.", courseName, courseId);
        if (apiKey == null || apiKey.isBlank()) return template;
        String prompt = String.format(
                "Write a single polite, professional paragraph (2-3 sentences) reminding an employee named %s "
                + "that they have not completed the course '%s' (Course ID: %s). "
                + "Do not use bullet points. Do not add a greeting or sign-off.", employeeName, courseName, courseId);
        String result = callGemini(prompt, apiKey);
        return result.isBlank() ? template : result;
    }

    /** Personalised intro paragraph for a mentor summary email. */
    public String mentorIntro(String mentorName, int pendingCount) {
        String template = String.format(
                "As part of our ongoing learning &amp; development tracking, we would like to bring to your "
                + "attention that <b>%d mentee(s)</b> under your guidance have not yet completed their "
                + "assigned courses. Please review the list below and follow up accordingly.", pendingCount);
        if (apiKey == null || apiKey.isBlank()) return template;
        String prompt = String.format(
                "Write a single polite, professional paragraph (2-3 sentences) to a mentor named %s, informing "
                + "them that %d of their mentees have not yet completed their assigned learning modules. "
                + "Ask them to follow up. Do not use bullet points. Do not add a greeting or sign-off.",
                mentorName, pendingCount);
        String result = callGemini(prompt, apiKey);
        return result.isBlank() ? template : result;
    }

    /** Executive summary paragraph for the CEO master-report email. */
    public String ceoIntro(String ceoName, int totalIncomplete, int totalDepts) {
        String template = String.format(
                "This is the master course-completion report generated by the Learning &amp; Development system. "
                + "A total of <b>%d active employee(s)</b> across <b>%d department(s)</b> have pending course "
                + "completions. The detailed breakdown is provided in the table below.", totalIncomplete, totalDepts);
        if (apiKey == null || apiKey.isBlank()) return template;
        String prompt = String.format(
                "Write a single concise, professional executive-summary paragraph (2-3 sentences) for a CEO "
                + "named %s, summarising that %d active employees across %d departments have not completed "
                + "their assigned learning courses. Do not use bullet points. Do not add a greeting or sign-off.",
                ceoName, totalIncomplete, totalDepts);
        String result = callGemini(prompt, apiKey);
        return result.isBlank() ? template : result;
    }

    // ------------------------------------------------------------------ //

    @SuppressWarnings("unchecked")
    private String callGemini(String prompt, String apiKey) {
        try {
            String url = String.format(GEMINI_URL, apiKey);

            HttpHeaders headers = new HttpHeaders();
            headers.setContentType(MediaType.APPLICATION_JSON);

            Map<String, Object> body = Map.of(
                    "contents", List.of(
                            Map.of("parts", List.of(Map.of("text", prompt)))
                    ),
                    "generationConfig", Map.of(
                            "maxOutputTokens", 200,
                            "temperature", 0.7
                    )
            );

            HttpEntity<Map<String, Object>> request = new HttpEntity<>(body, headers);
            ResponseEntity<Map> response = restTemplate.postForEntity(url, request, Map.class);

            if (response.getStatusCode().is2xxSuccessful() && response.getBody() != null) {
                List<Map<String, Object>> candidates =
                        (List<Map<String, Object>>) response.getBody().get("candidates");
                if (candidates != null && !candidates.isEmpty()) {
                    Map<String, Object> content  = (Map<String, Object>) candidates.get(0).get("content");
                    List<Map<String, Object>> parts = (List<Map<String, Object>>) content.get("parts");
                    if (parts != null && !parts.isEmpty()) {
                        return String.valueOf(parts.get(0).get("text"));
                    }
                }
            }
        } catch (Exception ignored) {
            // Silent fallback to template
        }
        // Fallback: return empty string so caller uses template
        return "";
    }
}

